# Generated by Django 3.2.7 on 2021-09-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20210904_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='order_id',
            field=models.CharField(db_index=True, editable=False, max_length=500, unique=True),
        ),
    ]
